#!/bin/bash
set -e

usage() {
	echo "Usage: $(basename $0) host [backup_file]" >&2
	exit 1
}

[[ $# == 1 ]] || [[ $# == 2 ]] || usage

host="$1"
[[ $# == 2 ]] && backup_file="${2}" || backup_file="/dev/stdout"

backup_command="mysqldump -u root --all-databases --skip-lock-tables"
ssh_command=""
if [[ "${host}" != "localhost" ]]; then
    ssh_command="ssh ${host} -C"
fi

${ssh_command} "${backup_command}|gzip" > ${backup_file}

