#!/bin/bash
set -e

usage() {
	echo "Usage: $(basename $0) host [backup_file]" >&2
	exit 1
}

[[ $# == 1 ]] || [[ $# == 2 ]] || usage

host="$1"
[[ $# == 2 ]] && backup_file="${2}" || backup_file="/dev/stdout"

ssh_command="ssh ${host} -C"
mysql_command="mysql -u root"
cat ${backup_file} | ${ssh_command} "gunzip -c - | ${mysql_command}"

